### ISSUE TITLE
standby cluster with s3 bucket v5.0.5

### ISSUE THREAD

**Issue by gkolvo** [CrunchyData/postgres-operator-examples#110]
Hi
I am trying to create standby cluster with using s3 bucket. 
It works only when I first did a backup on active db cluster with s3 repo. 
According to documentation it should take archive logs from s3 and run as standby cluster.

It seems that pgbackrest first try do a restore.
I am using helm chart and here is a values.yaml
```
 name: db-cluster
 instances:
   - name: database
     replicas: 2
     dataVolumeClaimSpec:
       accessModes:
       - "ReadWriteOnce"
       resources:
         requests:
           storage: 2Gi
       storageClassName: "rook-cephfs"
     walVolumeClaimSpec:
       accessModes:
       - "ReadWriteOnce"
       resources:
         requests:
           storage: 1Gi
       storageClassName: "rook-cephfs"
     affinity:
       podAntiAffinity:
         preferredDuringSchedulingIgnoredDuringExecution:
         - weight: 1
           podAffinityTerm:
             topologyKey: kubernetes.io/hostname
             labelSelector:
               matchLabels:
                 postgres-operator.crunchydata.com/cluster: db-cluster
                 postgres-operator.crunchydata.com/instance-set: database

 patroni:
   dynamicConfiguration:
     synchronous_mode: true
     postgresql:
       parameters:
         synchronous_commit: "on"
       pg_hba:
         - "local all postgres peer"
         - "local all postgres md5"
         - "local all crunchyadm peer"
         - "host all postgres 0.0.0.0/0 md5"
         - "host replication primaryuser 0.0.0.0/0 md5"
 standby:
   enabled: true
   repoName: repo2
 pgBackRestConfig:
   repos:
   - name: repo1
     volume:
       volumeClaimSpec:
         accessModes:
         - "ReadWriteOnce"
         resources:
           requests:
             storage: 1Gi
     schedules:
       full: "0 1 * * *"
       incremental: "0 */4 * * *"
   - name: repo2
     s3:
       bucket: "S3BUCKET_NAME"
       endpoint: "S3BUCKET_ENDPOINT"
       region: "S3BUCKET_REGION"
     schedules:
       full: "0 1 * * *"
       incremental: "0 */4 * * *"
   manual:
     repoName: repo1
     options:
      - --type=full
   global:
     repo1-retention-full: "14"
     repo1-retention-full-type: time
     repo2-path: "/pgbackrest/db-cluster/repo2"
     repo2-type: "s3"
     repo2-s3-key: "S3_KEY"
     repo2-s3-key-secret: "S3_SECRET"
     repo2-s3-verify-tls: "n"
     repo2-storage-port: "S3_PORT"
     repo2-s3-uri-style: "path"
     repo2-retention-full: "14"
     repo2-retention-full-type: time
     log-level-console: "debug"
     log-level-file: "debug"
     start-fast: "y"
```
This is what I get from logs:
```
│ database WARN: repo2: [BackupSetInvalidError] no backup sets to restore                                                                                                                               │
│ database ERROR: [075]: no backup set found to restore                                                                                                                                                 │
│ database 2022-04-13 12:37:27,167 ERROR: Error creating replica using method pgbackrest: 'bash' '-ceu' '--' 'install --directory --mode=0700 "${PGDATA?}" && exec "$@"' '-' 'pgbackrest' 'restore' '-- │
│ database 2022-04-13 12:37:27,167 ERROR: failed to bootstrap clone from remote master None
```

Thanks in advance,
Regards,
Grzegorz

**Comment by benjaminjb** [comment]
Thanks for the info, but I was unable to replicate this, and just to check, this is what I did:

1) Running PGO 5.2 in a k8s 1.23 environment
2) Started up a postgres cluster (`hippo`) with s3 backup
3) Started a second postgres cluster with `standby` enabled, with a local backup itself, and the standby pointed to the s3 repo from the `hippo` cluster

Just to double-check, can you share the values you used for the first postgres cluster? I'm particular curious about the path -- like, here, you have `repo2-path: "/pgbackrest/db-cluster/repo2"`, and I want to make sure that this path matches the path used in the non-standby cluster.

**Comment by benjaminjb** [comment]
No, wait, hold on: I was trying in 5.2, but you specified 5.0.5, so I reran the test with that, and yes, I am getting the same error as you. Let me check something.

**Comment by gkolvo** [comment]
Hi,
As I remember I saw this few time, after that I put workaround that full backup is done automatically after deployment.
I will check this on pgo 5.2.0 in the near future.

**Comment by andrewlecuyer** [comment]
From what I am seeing here, everything seems to be working as designed.

> It seems that pgbackrest first try do a restore.

That is correct - when creating a standby cluster as configured in the spec you provided:

```yaml
 standby:
   enabled: true
   repoName: repo2
```

...a restore will be done against S3 repository configured for `repo2`.

> full backup is done automatically after deployment.

That makes sense, i.e. a full backup is first needed in the the repo being used to create the standby (which in this case means a full backup is needed in `repo2`).

I am therefore proceeding with closing this one since we have not been able to reproduce any issues with standby creation, but just let us know if you continue to have trouble.
