### ISSUE TITLE
PgBackRest: Restore is never executed

### ISSUE THREAD

**Issue by sjstoelting** [CrunchyData/postgres-operator-examples#142]
Environment: minikube, kustomize->high-availability
postgres-operator-examples version tag: v5.0.0-alpha.4-0

Documented at https://access.crunchydata.com/documentation/postgres-operator/5.1.2/tutorial/disaster-recovery/#perform-a-point-in-time-recovery-pitr

Expected behavior: Point in time backup restored
Observed behavior: No backup is ever restored

Configuration:

```yaml
  backups:
    pgbackrest:
      restore:
        enabled: true
        repoName: repo1
        options:
        - --type=time
        - --target="2022-07-18 08:36:04.204224+00"
      global:
        repo1-retention-full: "3"
        repo1-retention-full-type: count
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:ubi8-2.38-1
      repos:
      - name: repo1
        schedules:
          full: "*/20 * * * 1-5" 
        volume:
          volumeClaimSpec:
            accessModes:
            - "ReadWriteOnce"
            resources:
              requests:
                storage: 1Gi
```

Steps to reproduce

```shell
minikube  start --memory 16384 --cpus 6 --disk-size 80000mb

kubectl apply -k kustomize/install/namespace
kubectl apply --server-side -k kustomize/install/default
kubectl apply -k kustomize/high-availability/

PG_CLUSTER_PRIMARY_POD=$(kubectl get pod -n postgres-operator -o name \
  -l postgres-operator.crunchydata.com/cluster=hippo-ha,postgres-operator.crunchydata.com/role=master)

kubectl exec --stdin -n postgres-operator --tty "${PG_CLUSTER_PRIMARY_POD}" -- /bin/bash

psql -c "CREATE DATABASE testdb"

pgbench -i -s 200 testdb

psql -c "SELECT current_timestamp, pg_size_pretty(pg_database_size('testdb'))"
       current_timestamp       | pg_size_pretty 
-------------------------------+----------------
 2022-07-18 08:36:04.204224+00 | 2999 MB
(1 row)

exit

#
kubectl exec --stdin -n postgres-operator --tty  hippo-ha-repo-host-0 -- /bin/bash
pgbackrest info

exit

kubectl exec --stdin -n postgres-operator --tty "${PG_CLUSTER_PRIMARY_POD}" -- /bin/bash

psql -c "DROP DATABASE testdb"

exit

# Add timestamp to ha-postgresql.yaml and set enabled=true

kubectl annotate -n postgres-operator postgrescluster hippo-ha --overwrite \
  postgres-operator.crunchydata.com/pgbackrest-restore=id1

```
