### ISSUE TITLE
s3 backup job is not triggering

### ISSUE THREAD

**Issue by alvibd** [CrunchyData/postgres-operator-examples#16]
I am trying to take backup of postgres database using Crunchydata postgres-operator version 5.0.1, in a bare metal s3 minIO bucket. When I run my pgbackrest using persistent volume claims the cluster runs a job to take back up after the cluster is up and running, but when I try to take backup using s3 bucket the job does not get triggered. In my kustomize folder I have the following
```
# postgres.yml
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: hippo
spec:
  image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres-ha:centos8-13.3-1
  postgresVersion: 13
  instances:
    - name: instance1
      walVolumeClaimSpec:
        accessModes:
        - "ReadWriteMany"
        resources:
          requests:
            storage: 1Gi
      replicas: 2
      dataVolumeClaimSpec:
        storageClassName: managed-nfs-storage
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: 1Gi
  backups:
    pgbackrest:
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:centos8-2.33-1
      repoHost:
        dedicated: {}        
      configuration:
      - secret:
          name: pgo-s3-creds
      global:
        repo1-path: /pgbackrest/postgres-operator/hippo-s3/repo1
      repos:
      - name: repo1
        s3:
          bucket: "pgbackup"
          endpoint: "192.168.10.222:9000"
          region: "None"
      manual:
        repoName: repo1
        options:
         - --type= full
  patroni:
    dynamicConfiguration:
      postgresql:
        parameters:
          max_parallel_workers: 2
          max_worker_processes: 2
          shared_buffers: 1GB
          work_mem: 2MB
        log:
          dir: /pgdata/pglog/
        pg_hba:
        - host all all 0.0.0.0/0 md5
        - host replication rep_user 0.0.0.0/0 md5
        - host replication rep_user 127.0.0.1/32 md5
```
in s3.conf:
```
[global]
#repo1-s3-key=SSKCGIL8403FN3QX9TQG
#repo1-s3-key-secret=9hY5cm8aTg27LIJ3m8JOJME8SNUYLLC3GRMAyA2A
repo1-s3-key=minio
repo1-s3-key-secret=miniostorage
```
and in kustomize.yaml:
```
namespace: postgres-operator

secretGenerator:
- name: pgo-s3-creds
  files:
  - s3.conf
generatorOptions:
  disableNameSuffixHash: true
resources:
- postgres.yaml
```
and `# kubectl -n postgres-operator describe pod hippo-repo-host-0`  returns this:
```
Name:         hippo-repo-host-0
Namespace:    postgres-operator
Priority:     0
Node:         dfsworker1/192.168.10.113
Start Time:   Sun, 29 Aug 2021 09:23:40 +0000
Labels:       controller-revision-hash=hippo-repo-host-66f7bcd589
              postgres-operator.crunchydata.com/cluster=hippo
              postgres-operator.crunchydata.com/pgbackrest=
              postgres-operator.crunchydata.com/pgbackrest-dedicated=
              postgres-operator.crunchydata.com/pgbackrest-host=
              statefulset.kubernetes.io/pod-name=hippo-repo-host-0
Annotations:  cni.projectcalico.org/containerID: a74bf3e4affdbf527bc2c568a0a9534074d7c82fc77ca1f13c7b940ff717ba40
              cni.projectcalico.org/podIP: 192.168.78.134/32
              cni.projectcalico.org/podIPs: 192.168.78.134/32
Status:       Running
IP:           192.168.78.134
IPs:
  IP:           192.168.78.134
Controlled By:  StatefulSet/hippo-repo-host
Init Containers:
  nss-wrapper-init:
    Container ID:  docker://433e906448b50b3e709caa58aa530854baccbb9b55839b2cdb80e9db515e255d
    Image:         registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:centos8-2.33-1
    Image ID:      docker-pullable://registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest@sha256:c5ae9cd667a1b814e2154d2135b9af614f96ce242b566eb858ad7177b94eecc8
    Port:          <none>
    Host Port:     <none>
    Command:
      bash
      -c
      NSS_WRAPPER_SUBDIR=postgres CRUNCHY_NSS_USERNAME=postgres CRUNCHY_NSS_USER_DESC="postgres" /opt/crunchy/bin/nss_wrapper.sh
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Sun, 29 Aug 2021 09:23:43 +0000
      Finished:     Sun, 29 Aug 2021 09:23:43 +0000
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /tmp from tmp (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-cxjt5 (ro)
Containers:
  pgbackrest:
    Container ID:  docker://42c780965284a65acb8733a92a4f22cdb70df76e4c9a000bee405896dc06f07e
    Image:         registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:centos8-2.33-1
    Image ID:      docker-pullable://registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest@sha256:c5ae9cd667a1b814e2154d2135b9af614f96ce242b566eb858ad7177b94eecc8
    Port:          <none>
    Host Port:     <none>
    Command:
      /usr/sbin/sshd
      -D
      -e
    State:          Running
      Started:      Sun, 29 Aug 2021 09:23:45 +0000
    Ready:          True
    Restart Count:  0
    Liveness:       tcp-socket :2022 delay=0s timeout=1s period=10s #success=1 #failure=3
    Environment:
      LD_PRELOAD:          /usr/lib64/libnss_wrapper.so
      NSS_WRAPPER_PASSWD:  /tmp/nss_wrapper/postgres/passwd
      NSS_WRAPPER_GROUP:   /tmp/nss_wrapper/postgres/group
    Mounts:
      /etc/pgbackrest/conf.d from pgbackrest-config (rw)
      /etc/ssh from ssh (ro)
      /tmp from tmp (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-cxjt5 (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  ssh:
    Type:                Projected (a volume that contains injected data from multiple sources)
    ConfigMapName:       hippo-ssh-config
    ConfigMapOptional:   <nil>
    SecretName:          hippo-ssh
    SecretOptionalName:  <nil>
  pgbackrest-config:
    Type:                Projected (a volume that contains injected data from multiple sources)
    SecretName:          pgo-s3-creds
    SecretOptionalName:  <nil>
    ConfigMapName:       hippo-pgbackrest-config
    ConfigMapOptional:   <nil>
  tmp:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  16Mi
  kube-api-access-cxjt5:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason       Age   From               Message
  ----     ------       ----  ----               -------
  Normal   Scheduled    65s   default-scheduler  Successfully assigned postgres-operator/hippo-repo-host-0 to dfsworker1
  Warning  FailedMount  65s   kubelet            MountVolume.SetUp failed for volume "ssh" : secret "hippo-ssh" not found
  Normal   Pulled       63s   kubelet            Container image "registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:centos8-2.33-1" already present on machine
  Normal   Created      62s   kubelet            Created container nss-wrapper-init
  Normal   Started      62s   kubelet            Started container nss-wrapper-init
  Normal   Pulled       61s   kubelet            Container image "registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:centos8-2.33-1" already present on machine
  Normal   Created      60s   kubelet            Created container pgbackrest
  Normal   Started      60s   kubelet            Started container pgbackrest
  ```
Additionally,
```
# kubectl -n postgres-operator logs hippo-repo-host-0
Server listening on 0.0.0.0 port 2022.
Server listening on :: port 2022.
kex_exchange_identification: Connection closed by remote host
kex_exchange_identification: Connection closed by remote host
Accepted publickey for postgres from 192.168.122.18 port 39112 ssh2: ECDSA SHA256:f7En+B4/XFxR3Eu0ZqtPNIahYaVtxIn/LkmclRJqpho
kex_exchange_identification: Connection closed by remote host
kex_exchange_identification: Connection closed by remote host
Accepted publickey for postgres from 192.168.122.19 port 53796 ssh2: ECDSA SHA256:f7En+B4/XFxR3Eu0ZqtPNIahYaVtxIn/LkmclRJqpho
kex_exchange_identification: Connection closed by remote host
```
`# kubectl -n postgres-operator get pods` returns:
```
NAME                                      READY   STATUS    RESTARTS   AGE
hippo-instance1-ggst-0                    3/3     Running   0          20m
hippo-instance1-j67m-0                    3/3     Running   0          20m
hippo-repo-host-0                         1/1     Running   0          20m
nfs-client-provisioner-7d485f5b8d-l88ts   1/1     Running   0          3h9m
pgo-54ff6dc755-ct4bl                      1/1     Running   0          3h7m
```
Is there anyone who can tell me if I am misconfiguring anything regarding minio configurations? my kubernetes version is 1.22
