### ISSUE TITLE
Documentation for s3 pgbackrest with Helm

### ISSUE THREAD

**Issue by SolomonHD** [CrunchyData/postgres-operator-examples#20]
Hello,

I have two issues:

1) Can I get an example of setting up pgbackrest repo with s3 buckets using Helm instead of kustomize? Helm has worked better in general.

2) I could not get the kustomize s3 example to work. The secret does not get created.

**Comment by jkatz** [comment]
> Can I get an example of setting up pgbackrest repo with s3 buckets using Helm instead of kustomize? 

Yes, one will be added int he fullness of time, though we gladly will accept contributions.

> I could not get the kustomize s3 example to work. The secret does not get created.

Did you use the steps in the [tutorial](https://access.crunchydata.com/documentation/postgres-operator/v5/tutorial/backups/#using-s3)?

If not, what commands did you run? Is there any output why the Secret failed to be created?

**Comment by SolomonHD** [comment]
I would gladly contribute to the readme if you could help me out with the helm syntax: here's what I have so far :
```yaml
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: {{ .Values.name }}
spec:
  image: {{ .Values.postgres }}
  postgresVersion: {{ .Values.postgresVersion }}
  instances:
    - name: instance1
      dataVolumeClaimSpec:
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: 2Gi
  users:
   - name: postgres
  backups:
    pgbackrest:
      image: {{ .Values.pgBackRest}}
      configuration:
        - secret:
            name: s3-secret
      global:
        repo3-path: /pgbackrest/postgres-operator/hippo-s3/repo3
      repoHost:
        dedicated: {}
      repos:
      - name: repo3
        s3:
          bucket: bucket_name
          endpoint: endpoint
          region: region
  proxy:
    pgBouncer:
      image: {{ .Values.pgBouncer}}
---
apiVersion: v1
kind: Secret
metadata:
  name: s3-secret
data:
{{- range $key, $value := .Values.secret.global }}
  {{ $key }}: {{ $value |b64enc }}
{{- end }}
```

and in the values.yaml file I have
```yaml
secret:
  global:
   repo3-s3-key: AWS_KEY
   repo3-s3-key-secret: AWS_SECRET
```
With this config the secret actually does get created but the operator doesn't seem to be using it.
