### ISSUE TITLE
Add feature gate support to helm chart

### ISSUE THREAD

**Issue by thefirstofthe300** [CrunchyData/postgres-operator-examples#262]
It would be really nice if the Helm chart supported feature gates. Currently, there is no way to inject a custom env value into the chart manifest so feature gates are essentially non-operable.

**Comment by jbperrin88** [comment]
This feature is also wanted here ;p
We would like to add proxy settings via Env variable to the manager deployement for pgo

**Comment by benjaminjb** [comment]
Sounds reasonable to me to have a way to add env vars to the Helm chart -- I'm making a ticket in our backlog for it, but I'd also welcome a PR if anyone wants to take a swing at it.

**Comment by jaitaiwan** [comment]
I just came across this issue when trying to enable AutoGrow volumes. I've added a PR which addresses the problem with a number of potential ways to solve.

I'd like to ask that the chart version also be disconnected from the PGO version. That will ensure that folks that use gitops tools like flux are able to pick up the change because of the bumped chart version.

**Comment by jaitaiwan** [comment]
Hey folks I wanted to highlight [patches](https://medium.com/@tharukam/generate-kubernetes-manifests-with-helm-charts-using-kustomize-2f82ab5c5f11) that are something that you can use to patch the helm charts after generation using kustomize.

Here's an example patch I'm using for adding a feature flag:
```
patches:
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: PGO_FEATURE_GATES
        value: AutoGrowVolumes=true
  target:
    group: apps
    version: v1
    kind: Deployment
    name: pgo
```

You can find more information about [patches here](https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/patches/). If you're using flux gitops like me then [here's a link](https://fluxcd.io/flux/components/helm/helmreleases/#post-renderers) to that too in the meantime.

I also found [this post](https://fabianlee.org/2022/04/15/kubernetes-kustomize-transformations-with-patchesjson6902/) very useful to understand how to modify maps and arrays.
