### ISSUE TITLE
PGBouncer config

### ISSUE THREAD

**Issue by rgherta** [CrunchyData/postgres-operator-examples#81]
Can we atm customize the pgbouncer settings like max_conn etc ?
the config file is managed by the operator and I see nothing helpful in the CRDs.

**Comment by alrooney** [comment]
Hi @rgherta I believe you can customize pgbouncer by editing the postgrescluster definition and adding something like the following: 
```
spec:
  proxy:
    pgBouncer:
      config:
        global:
          pool_mode: transaction
          max_client_connection: 200
```
