### ISSUE TITLE
Helm Chart doesn't contain schedule for backups?

### ISSUE THREAD

**Issue by jfmatth** [CrunchyData/postgres-operator-examples#92]
Thank you for the latest PGO, it's amazing, and fully Kubernetes, no more command line pgo:)

I'm hoping it's me, but I don't see anywhere in the HELM values.yaml file for the backup schedule, did I just not see it?

I'm hoping I can add to the template, but was hoping smarter HELM people than me would

**Comment by nawarajshahi** [comment]
@jfmatth do you mean something like this? 
```
backups:
  pgbackrest:
    configuration:
      secret: pgo-s3-creds
    global:
      repo1-path: /postgres-operator/repo1
      repo1-retention-full: "14"
      repo1-retention-full-type: time
    repos:
      - name: repo1 #backup repo to keep backup on s3 if you're using s3
        schedules:
          full: "0 8 * * *"
        s3:
          bucket: "s3-bucket-name"
          endpoint: "s3.amazonaws.com" #s3 endpoint
          region: "us-east-1" #s3 region
      - name: repo2 #local volume to keep backup locally
        schedules:
          full: "0 8 * * *"
        volume:
          volumeClaimSpec:
            storageClassName: gp3 #(whatever the storageClassName you have, ignore if you're using default)
            accessModes:
            - "ReadWriteOnce"
            resources:
              requests:
                storage: 500Gi #specify local volume  size here
```
This one does 4am UTC but you can use https://crontab.guru/ to populate your schedules. 
Hope this helps!

**Comment by jfmatth** [comment]
@nawarajshahi Thank you for the response :)

Yes and No, it gives me more insight to the details of CRON for PGO, but i was really hoping to see a HELM chart in the examples, but it's harder than it looks after googling for HELM cronjob 

I'll have a look over and work it into my environment.

thanks again

**Comment by tfk-ben** [comment]
@jfmatth  this is worked for me:
for the helm **values.yaml**:
```yaml
pgBackRestConfig:
  global:
    repo1-retention-full: "4" # Keep 4 full backups
    repo1-retention-diff: "7" # Keep 7 differential backups
    repo1-type: gcs
    repo1-path: /dev-backup

  configuration:
  - secret:
      name: pgo-gcs-creds # GCS credentials
  - configMap:
      name: pgbackrest-config # pgbackrest config

  repos:
  - name: repo1
    schedules:
      full: "0 1 * * 0" # Weekly full backup on Sundays at 1 AM
      differential: "0 1 * * 1-6" # Daily differential backup on Mon-Sat at 1 AM
    gcs:
      bucket: "my-bucket"

  manual:
    repoName: repo1
    options:
    - --type=full
   
```
And for **pgo-gcs-creds** and  **pgbackrest-config**
``` yaml
apiVersion: v1
kind: Secret
metadata:
  name: pgo-gcs-creds
  namespace: pg
stringData:
  gcs-key.json: |-
    {
    Your gcs key
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pgbackrest-config
  namespace: pg
data:
  db.conf: |-
    [global]
    compress-level=6
    start-fast=y
    process-max=20
```
